# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb16459f95fde3a7e00e8e1f3edba06671eaa24de25c656ed826612ce05451bf4d584c155a1d2f782a1be6ad941c621a179d295277e390c285929a8eaf70eadb

test:
  secret_key_base: 5efc7fba4f608d54522cb1e21434b3384f473b75560cc47aa0c69ee62d131206cc8a9131979b27f2743d1ae892d9f1527661b02b2e155bcc7cfbf4bab20001c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
